application:
  default_host: ~
  default_from: ~

analytics:
  web_property_id: ~

contact:
  email: ~

s3:
  upload_bucket: ~

import:
  access_token: ~
  repo: waynegraham/dlme-metadata
  properties:
    exhibit_slug: library
    # Because we're using background jobs, we don't use a thread pool.
    # Using a threadpool would require a larger ActiveRecord connection pool
    processing_thread_pool: 0
  sources:
    penn_tei:
      directory: manuscript/records/penn/schoenberg
      traject_file: tei_config
      properties:
        agg_provider: University of Pennsylvania Library
        inst_id: penn
    stanford_mods:
      directory: maps/records/stanford
      traject_file: stanford_mods_config
      properties:
        agg_provider: Stanford Libraries
        agg_data_provider: Stanford Libraries
        inst_id: stanford
    met_csv:
      directory: museum/records
      only: !ruby/regexp '/met_museum_records.csv/'
      traject_file: met_csv_config
      properties:
        agg_provider: Metropolitan Museum of Art
        inst_id: met
    princeton_mods:
      directory: movie-posters/records/princeton
      traject_file: mods_config
      properties:
        agg_provider: Princeton University Library
        agg_data_provider: Princeton University Library
        inst_id: princeton
    numismatics:
      directory: coins
      traject_file: numismatic_csv_config
      properties:
        agg_provider: American Numismatic Society
        inst_id: ans
    penn_egyptian:
      directory: museum/records
      only: !ruby/regexp '/egyptian-20170820.csv/'
      trajact_file: penn_egyptian_config
      properties:
        agg_provider: Penn Museum
        inst_id: penn_museum
